#    format:
#      0: yuv2
#      1: mjpeg
#      2: bgr24
cameras:
  - open: False
    device: '/dev/video0'
    format: 1
    fps: 30
    width: 1280
    height: 720
    pub_topic: '/circle_cameras_middle_cam'

  - open: True
    device: '/dev/video2'
    format: 1
    fps: 30
    height: 720
    width: 1280
    pub_topic: '/circle_cameras_left_cam'

  - open: True
    device: '/dev/video4'
    format: 1
    fps: 30
    height: 720
    width: 1280
    pub_topic: '/circle_cameras_rear_cam'

  - open: False
    device: '/dev/video6'
    format: 1
    fps: 20
    width: 1280
    height: 720
    pub_topic: '/circle_cameras_right_cam'

